version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: attend_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"
    networks:
      - attend-network

  db:
    image: mysql:8.0
    container_name: attend_db
    restart: always
    environment:
      MYSQL_DATABASE: attend_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - attend-network

volumes:
  db_data:

networks:
  attend-network:
    driver: bridge
