[build]
builder = "nixpacks"
buildCommand = "bash deploy-simple.sh"

[deploy]
healthcheckPath = "/test.php"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = "cd src && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"

[env]
PORT = "8000"

# Core Application Settings
APP_NAME = "AttendEase"
APP_ENV = "production"
APP_DEBUG = "true"
APP_KEY = "base64:bu0WlbKjnT8/vfjdNkrL3g5wKj/0BzCnKcgcDm3372U="
APP_URL = "https://attendease-production-14cb.up.railway.app"
APP_TIMEZONE = "UTC"

# Localization
APP_LOCALE = "en"
APP_FALLBACK_LOCALE = "en"
APP_FAKER_LOCALE = "en_US"

# Database Configuration (Production)
DB_CONNECTION = "mysql"
DB_HOST = "metro.proxy.rlwy.net"
DB_PORT = "29939"
DB_DATABASE = "railway"
DB_USERNAME = "root"
DB_PASSWORD = "ixOxZEOACaqQzVjzlFbnaDDeyMqErqRg"

# Session & Cache
SESSION_DRIVER = "file"
SESSION_LIFETIME = "120"
SESSION_ENCRYPT = "false"
CACHE_STORE = "file"
QUEUE_CONNECTION = "sync"

# Logging (Debug enabled for troubleshooting)
LOG_CHANNEL = "stack"
LOG_LEVEL = "debug"
LOG_STACK = "single"

# Mail Configuration
MAIL_MAILER = "log"
MAIL_FROM_ADDRESS = "noreply@attendease.app"
MAIL_FROM_NAME = "AttendEase"
MAIL_HOST = "127.0.0.1"
MAIL_PORT = "2525"

# File Storage
FILESYSTEM_DISK = "local"
BROADCAST_CONNECTION = "log"

# Security & Performance
BCRYPT_ROUNDS = "12"
PHP_CLI_SERVER_WORKERS = "4"

# Maintenance
APP_MAINTENANCE_DRIVER = "file"nixpacks"
buildCommand = "bash deploy-simple.sh"

[deploy]
healthcheckPath = "/test.php"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = "cd src && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"

[env]
PORT = "8000"
APP_ENV = "production"
APP_DEBUG = "true"
APP_NAME = "AttendEase"
APP_URL = "https://attendease-production.up.railway.app"
LOG_LEVEL = "debug"
APP_DEBUG = "true"
APP_KEY = "base64:YWRlYmMxNGRlYzM5MzMyNjQyYjFlZWI5NzQ4MGI4Y2IK"
