[build]
builder = "nixpacks"
buildCommand = "bash deploy-simple.sh"

[deploy]
healthcheckPath = "/test.php"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = "cd src && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"

[env]
PORT = "8000"
APP_ENV = "production"
